#!/bin/bash

# Setup for USB to CAN adapter
# Manufacturer:  www.ixxat.com
# Adapter details: Ixxat USB-to-CAN V2 professional
# P/N: 1.01.0283.22002

# Side effect: Restarts network

#--------------------
# setup can interface
#--------------------

# this directory
DIR=`pwd`

# get build enviroment, download driver and build kernel module 
yes | sudo apt-get install module-assistant \
linux-headers-generic linux-headers-5.0.0-19-generic \
can-utils

sudo module-assistant prepare
sudo modprobe can

# download and unpack
mkdir -p ~/Repositories/
cd ~/Repositories/
git clone https://github.com/ilanist/Ixxat_usb_to_can_linux-headers-5.0.0-19-generic.git
cd Ixxat_usb_to_can_linux-headers-5.0.0-19-generic/candriver
# build and install
yes | make && sudo make install
cd $DIR

# update network config if needed
BITRATE=1000000
NET=/etc/network/interfaces #footest #/etc/network/interfaces
BAK=/etc/network/interfaces.can.bak #footest.can.bak #/etc/network/interfaces.can.bak
ID_STR="# This configuration was written by setupCAN"
CONFIG_WRITTEN_BEFORE_CMD=`echo \`grep "$ID_STR" "$NET" | wc -l\``

# if the config file already has config, do not write.
if [ "$CONFIG_WRITTEN_BEFORE_CMD" = "0" ]

# need new config
then
	# backup
	sudo cp -b "$NET" "$BAK"
	# configure
	sudo sh -c "echo \"\" >> $NET"
	sudo sh -c "echo \"$ID_STR\" >> $NET"
	sudo sh -c "echo \"# Setup CAN Network for USB to CAN adapter (Ixxat USB-to-CAN V2 professional)\" >> $NET"
	sudo sh -c "echo \"ip link set can0 type can bitrate $BITRATE\" >> $NET"
	sudo sh -c "echo \"ip link set up can0\" >> $NET"
	sudo sh -c "echo \"ip link set can1 type can bitrate $BITRATE\" >> $NET"
	sudo sh -c "echo \"ip link set up can1\" >> $NET"
	echo "Network config updated, written to: $NET"
	echo "Restarting network services..."
	# restart network
	sudo /etc/init.d/networking restart
	echo "...Done"
else # do not touch config
	echo "Network config is up to date, nothing written to: $NET"
fi

